version: '3'

services:
    cache: 
        image: redis:latest
        expose: 
            - 6379
        ports: 
            - "6379:6379"
        container_name: cache
        
    app:
        build: .
        depends_on:
            - cache

    

